services:
  nsd:
    image: ghcr.io/the-kube-way/nsd:latest
    read_only: true
    tmpfs:
      - /tmp
      - /var/db/nsd
    volumes:
      - ./nsd/conf:/etc/nsd:ro
      - ./nsd/zones:/zones
    ports:
      - $DNS_PORT:53/udp
